# Numpy

In [2]:
import numpy as np

### Básico

In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b = np.array([[1.0,3.0],[2.0,4.0]])
print(b)

[[1. 3.]
 [2. 4.]]


### Dimensões

In [ ]:
a.ndim # Contar quantas dimensões ela tem

1

In [ ]:
b.ndim # Contar quantas dimensões ela tem

2

In [ ]:
a.shape # Formato da matriz

(3,)

In [10]:
b.shape # Formato da matriz

(2, 2)

In [17]:
a.dtype # Verificar o tipo do dado

dtype('int64')

In [19]:
a.itemsize # Tamanho de cada item, em bytes

8

In [20]:
b.itemsize # Tamanho de cada item, em bytes

8

In [23]:
# Se sabemos que o array não terá tanto espaço com números, podemos mudar o formato de bytes dele para ocupar menos espaço.

idade = np.array([1,2,3,5,7,10,17,29], dtype='int8')
idade.dtype

dtype('int8')

In [25]:
idade.itemsize # Agora cada item ocupa 1 bytes

1

In [28]:
idade.nbytes # Total de bytes do array

8


### Manipulação em Linhas e Colunas

In [3]:
a = np.array([[1,2,3,4,5,6,7], [8,9,1,2,3,4,5]])
print(a, a.shape)

[[1 2 3 4 5 6 7]
 [8 9 1 2 3 4 5]] (2, 7)


In [4]:
# Pegar um item específico [linha, coluna]
a[0,4]

np.int64(5)

In [5]:
# Funciona com valores negativos, igual lista
a[1,-1]

np.int64(5)

In [6]:
# Pegar uma coluna específica -> pegar a 3ª coluna
a[:,2]

array([3, 1])

In [11]:
# Percorrendo a lista de 2 em 2
a[1, 0::2]

array([8, 1, 3, 5])

In [16]:
# Invertendo as linhas
a[::-1,:]

array([[8, 9, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 6, 7]])

In [17]:
# Invertendo as colunas
a[:,::-1]

array([[7, 6, 5, 4, 3, 2, 1],
       [5, 4, 3, 2, 1, 9, 8]])

### Exemplo 3D - Tridimensional

In [22]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [23]:
# Quantas dimensões?
b.ndim

3

In [24]:
# Pegar um elemento específico(trabalhamos de fora para dentro)
# Primeira matriz [0]
b[0]

array([[1, 2],
       [3, 4]])

In [ ]:
# Acessar a segunda linha da primeira matriz
b[0,1]

array([3, 4])

In [27]:
# Primeiro elemento da segunda linha da primeira matriz
b[0,1,0]

np.int64(3)

In [32]:
# Primeira linha da segunda dimensão
b[1,0,:]

array([5, 6])

In [35]:
# Segunda coluna da primeira dimensão
b[0, :, 1]

array([2, 4])

## Inicializando tipos diferente de Arrays

### Zeros/Ones

In [2]:
import numpy as np

In [39]:
# Criando um array de 0s
np.zeros(3)

array([0., 0., 0.])

In [45]:
# Criando um array de 3 linhas e 5 colunas apenas de 0s
# Matriz, linha, colunas
np.zeros([3,5,2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
np.ones([4,2,2])
#np.ones([4,2,2], dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

### Outros números/aleatórios

In [52]:
# Qualquer outro número
# passe o tamanho da matriz primeiro e depois o número que você quer que seja preenchido, no caso abaixo é uma amtriz 3 por 3 com números 21
np.full([3,3],21)

array([[21, 21, 21],
       [21, 21, 21],
       [21, 21, 21]])

In [54]:
np.full([7,7], 17)

array([[17, 17, 17, 17, 17, 17, 17],
       [17, 17, 17, 17, 17, 17, 17],
       [17, 17, 17, 17, 17, 17, 17],
       [17, 17, 17, 17, 17, 17, 17],
       [17, 17, 17, 17, 17, 17, 17],
       [17, 17, 17, 17, 17, 17, 17],
       [17, 17, 17, 17, 17, 17, 17]])

In [56]:
# full_like method -> reutilização dos arrays para preenchimento
# primeiro declaramos a matriz que iremos transformar

a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [62]:
# Quero utilizar a estrutura da matriz "a" e preenche-la com números 7, eu não substituo os valores, apenas utilizo a estrutura
b = np.full_like(a, 7)
b

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

In [63]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [64]:
# Números aleatórios
# Decimais -> estamos trabalhando com .rand(), nessa função não precisamos passar uma lista dentro para informar o shape.
np.random.rand(2, 2, 3)

array([[[0.64057722, 0.22033749, 0.23115643],
        [0.78783722, 0.35603772, 0.03030005]],

       [[0.29714354, 0.7974781 , 0.50698534],
        [0.79956676, 0.54546837, 0.20812681]]])

In [65]:
# Random integers
# randint(limites, size=(shape))
np.random.randint(10, size=(3,4,5))

array([[[8, 8, 1, 4, 5],
        [6, 7, 2, 1, 5],
        [4, 3, 8, 8, 4],
        [6, 1, 8, 6, 7]],

       [[1, 7, 1, 1, 1],
        [9, 7, 4, 5, 0],
        [4, 0, 8, 6, 0],
        [0, 1, 2, 0, 7]],

       [[5, 3, 6, 6, 7],
        [6, 5, 0, 1, 7],
        [9, 4, 3, 9, 6],
        [8, 8, 9, 1, 0]]], dtype=int32)

In [ ]:
# Colocando número inicial e final
np.random.randint(4,9, size=(2,3,4))

array([[[5, 6, 4, 8],
        [5, 7, 5, 4],
        [8, 5, 5, 6]],

       [[8, 6, 5, 5],
        [7, 6, 7, 5],
        [5, 7, 5, 4]]], dtype=int32)

### Operações de algebra

In [5]:
# matriz identidade só precisa de 1 parametro, porque naturalmente ela é uma matriz quadrada
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Repetição de arrays em colunas
ex = np.array([1,2,3])
np.repeat(ex,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [14]:
# Repetição de arrays em linha
ex = np.array([[1,2,3]])
np.repeat(ex, 3, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

### Exercicio

In [ ]:
matriz = np.zeros([5,5], dtype="int8")
matriz

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [38]:
matriz[:,0] = 3 
matriz[:,4] = 3
matriz[4] = 3
matriz[0] = 5
matriz[2,2] = 15
matriz

array([[ 5,  5,  5,  5,  5],
       [ 3,  0,  0,  0,  3],
       [ 3,  0, 15,  0,  3],
       [ 3,  0,  0,  0,  3],
       [ 3,  3,  3,  3,  3]], dtype=int8)

## Aula 02

### Cuidado ao copiar matrizes

In [47]:
import numpy as np
a = np.array([1,2,3])
#b[0] = 256
b = a.copy()
b[0] = 256
b

array([256,   2,   3])

In [48]:
a

array([1, 2, 3])

#### a foi alterado por b, então para copiar uma matriz, temos que usar .copy()

In [49]:
b

array([256,   2,   3])

In [65]:
# element wise operations
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [58]:
# Soma 2 a todos os valores da matriz
a + 2

array([3, 4, 5, 6])

In [59]:
# Subtrai 2 a todos os valores da matriz
a - 2

array([-1,  0,  1,  2])

In [60]:
# Multiplica 2 a todos os valores da matriz
a * 2

array([2, 4, 6, 8])

In [61]:
# Potencia 2 em todos os valores da matriz
a ** 2

array([ 1,  4,  9, 16])

In [66]:
# É possível fazer atribuição também +=

a += 7
a

array([ 8,  9, 10, 11])

In [69]:
# element wise operations com dois arrays de mesmas dimensões
b = np.array([5, -5, 5, -5])
a - b

array([ 3, 14,  5, 16])

### Operações amtemáticas mais complexas

In [70]:
import math

In [75]:
# Multiplicando pelo valor de PI
a = np.array([1,2,3,4])
a = a * math.pi
a

array([ 3.14159265,  6.28318531,  9.42477796, 12.56637061])

In [79]:
# Cosceno
np.cos(a)

array([-1.,  1., -1.,  1.])

In [80]:
# Seno
np.sin(a)

array([ 1.2246468e-16, -2.4492936e-16,  3.6739404e-16, -4.8985872e-16])

### Linear Algebra

In [81]:
import numpy as np

In [85]:
a = np.ones([2,3])
print(a)

b = np.full([3,2], 5)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]


In [86]:
# Retorno de erro se tentarmos multiplicar matrizes de tamanhos diferentes
a * b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [89]:
# note inclusive que A X B != B X A
#np.matmul(a,b)
np.matmul(b,a)

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [90]:
# Encontrar o determinante
identidade = np.identity(3)
identidade

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [91]:
# Pra queme stá familiarizado com Algebra Linear, sabe que o determinante de uma amtriz identidade é = 1
np.linalg.det(identidade)

np.float64(1.0)

### Estatística Básica

In [102]:
dados = np.array([[1,2,3], [4,5,6]])
dados2 = np.random.randint(-50,50, size=(10,10))
dados2

array([[ 47,  39, -41,   6,  -8, -50,  17,  22,  10, -47],
       [-12,  14,   1,   7,   5, -40,  24,   4,  34,   7],
       [-15, -22,   7, -39, -11, -29, -24,  12,  -8,  39],
       [-10,  25, -38,  30,  28,  16,  36,  16,  45,  43],
       [ 39, -37,  19, -37,   1, -10, -47,  -1, -39,  30],
       [ 36, -20,   7,  33,  12, -27, -26,  41, -43, -28],
       [-17, -21,  37,  42,  -5, -44,  26,  48,  48, -22],
       [ 19, -24, -47, -17, -10,  13,  33, -13,   4, -33],
       [ -8,  43, -15, -47,  -5,  29, -36, -45,  13, -45],
       [  3, -13, -30,  20,  25, -25,  19, -16,   4,  29]], dtype=int32)

In [105]:
# Menor valor
np.min(dados2)

np.int32(-50)

In [106]:
# Maior valor
np.max(dados2)

np.int32(48)

In [109]:
# Pegando os valores de acordo com linhas e colunas, axis 0 é coluna, axis 1 é linha
print(np.min(dados2, axis=0))
print(np.min(dados2, axis=1))

[-17 -37 -47 -47 -11 -50 -47 -45 -43 -47]
[-50 -40 -39 -38 -47 -43 -44 -47 -47 -30]


In [112]:
# Soma
print(np.sum(dados2))
print(np.sum(dados2, axis=0))

-40
[  82  -16 -100   -2   32 -167   22   68   68  -27]


In [117]:
# Média
np.mean(dados2, axis=0)

array([  8.2,  -1.6, -10. ,  -0.2,   3.2, -16.7,   2.2,   6.8,   6.8,
        -2.7])

### Reorganização de Arrays

In [118]:
import numpy as np

In [119]:
matriz = np.array([[1,2,3,4], [5,6,7,8]])
matriz

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [127]:
# Desde que tenha o mesmo número de itens dentro do reshape, é válido -> brincar com esses valores
# Quero uma matriz com 2 linhas e 4 colunas
matriz.reshape([2,4])

# Quero uma matriz com 4 linhas e 2 colunas
matriz.reshape([4,2])

# Quero 8 linhas e 1 coluna
matriz.reshape([8,1])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

### Stack de Vetores -> Concatenação de vetores de mesma dimensão

In [130]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

# V stack -> o V significa Vertically, um stack vertical
np.stack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [132]:
# H stack -> o H significa Horizontally, um stack horizontal
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [135]:
# Realizar repetições e atribuir a uma variável
a = np.stack([v1,v1,v2,v2])
a

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

### Mudança de dtype

In [137]:
a.dtype

dtype('int64')

In [139]:
# Mudança de dtype
a = a.astype('float32')
a.dtype

dtype('float32')

In [140]:
a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [5., 6., 7., 8.],
       [5., 6., 7., 8.]], dtype=float32)

### Advanced Indexing

#### Boolean Masking

Em ciência da computação, boolean, ou lógico, é um tipo de dado primitivo que possuir dois valores, que podem ser consideramos como 0 ou 1, falso ou verdadeiro

In [141]:
import numpy as np

In [146]:
dados = np.random.randint(0, 20, size=(5,5))
dados

array([[13,  7,  8,  0, 17],
       [ 4,  4,  2,  8, 12],
       [13,  3,  4,  7, 16],
       [10, 18, 17,  7,  5],
       [17,  5,  4,  2, 15]], dtype=int32)

In [147]:
dados > 10

array([[ True, False, False, False,  True],
       [False, False, False, False,  True],
       [ True, False, False, False,  True],
       [False,  True,  True, False, False],
       [ True, False, False, False,  True]])

É possível fazer o array utlizando os indexes da máscara que foi criada anteriormente

Então no exemplo abaixo queremos dados onde os dados são maiores que 10

In [148]:
dados[dados > 10]

array([13, 17, 12, 13, 16, 18, 17, 17, 15], dtype=int32)

In [151]:
# A função "any" verifica se qualquer valor abte a requisição
np.any(dados > 10)

# É possível alterar e analisar por linhas e colunas
np.any(dados > 10, axis=0)
np.any(dados > 10, axis=1)

array([ True,  True,  True,  True,  True])

In [158]:
# O oposto da função any é a função "all", que só nos retorna TRUE se todos os valores do eixo são verdadeiros
np.all(dados > 10)

# Por linhas e colunas
np.all(dados > 10, axis=0)
np.all(dados > 10, axis=1)

array([False, False, False, False, False])

In [159]:
# Mais de uma condição
((dados > 10) & (dados < 15))

array([[ True, False, False, False, False],
       [False, False, False, False,  True],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [160]:
# É possível utilizar a notação NOT ~ negativa
~((dados > 10) & (dados < 15))

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

É possível acessar os dados via index no numpy, assim como em listas

In [161]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [163]:
# O primeiro colchete [] inicia a máscara e o segundo [] retorna os indices
a[[1,2,9]]

array([ 2,  3, 10])

In [167]:
# e note que indexes negativos também são válidos
a[[-1,-2,-5]] == a[[9, 8, 5]]

array([ True,  True,  True])

#### Desafio Final

In [170]:
m = np.arange(1,31).reshape([6,5])
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

##### Questões
1 - Façam um slice que retorne a última linha da matriz(utilize indexes negativos)
<br>
2 - Faça um slice na matriz que retorne uma matriz utilizando os números 19, 20, 24, 25
<br>
3 - Retorne a média dos valores das últimas 3 linhas
<br>
4 - Retorne a diagonal que vai do número 2 até o número 20
<br>
5 - Queremos o retorno sendo uma matriz do tipo:
<br>
4   5
<br>
24  25
<br>
29  30


In [173]:
# Resolução questão 01
ultima_linha = m[-1]
ultima_linha

array([26, 27, 28, 29, 30])

In [176]:
# Resolução questão 02
matriz_esp = m[3:5,3:5]
matriz_esp

array([[19, 20],
       [24, 25]])

In [ ]:
# Resolução questão 03
media_tres = m[3:6].mean()
#media_tres = m[-3,:].mean()
media_tres

np.float64(23.0)

In [203]:
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [229]:
# Resolução questão 04
#diagonal = np.array([[m[0,1]], [m[1,2]], [m[2,3]], [m[3,4]]])

                #linhas       #colunas
nova_diagonal = m[[0,1,2,3], [1,2,3,4]]
nova_diagonal

# Lembrando que é possível passar os indices que eu quero, igual faz em listas

array([ 2,  8, 14, 20])

In [216]:
nova_matriz = m[[0,4,5],3:5]
nova_matriz

array([[ 4,  5],
       [24, 25],
       [29, 30]])